### PR TITLE
koushik -2019A1PS0766P

### PR DESCRIPTION
**Pull request by koushik-4388**

### CODE REVIEW

**Review by twitu — CHANGES_REQUESTED** [review]
The assignment is not complete without test cases.

1. Take a look at some other submissions and add at least two simple tests for each problem. 
2. Move all your files to a single folder with your name, as given in the instructions.

**Comment by twitu** [comment]
You have messed up your file structure. I need you to make single directory name `koushik` with the complete problem files (including implementation and test cases) inside it. You have made a nested directory, please correct it before I can merge.

**Comment by koushik-4388** [comment]
i hope its correct now.

**Comment by twitu** [comment]
Remove the extra directory i.e. `koushik` inside `koushik`.

**Comment by twitu** [comment]
Take a look at this PR #5, which has been merged.

**Comment by koushik-4388** [comment]
how to remove the directory in github

**Comment by twitu** [comment]
delete file from local repository, then commit and push. Or maybe search for a specific tutorial guide you on this.

**Review by twitu — APPROVED** [review]

**Pull request merged**
