### PR TITLE
abhishek sharma 2019A4PS0468P

### PR DESCRIPTION
**Pull request by abhisharma76**

### CODE REVIEW

**Review by twitu — CHANGES_REQUESTED** [review]
Add at least two simple test cases for each problem and put the files in a folder of your name as given in the instructions.

**Comment by twitu** [comment]
Take a look at this PR #5, which has been merged.

**Comment by twitu** [comment]
@abhisharma76 please add the files inside a single directory before I can merge it.

**Comment by abhisharma76** [comment]
> @abhisharma76 please add the files inside a single directory before I can merge it.

is there any option by which i can add the uploaded files in a single directory or i'll have to upload it again

**Comment by 7vik** [comment]
@abhisharma76 you'll need to do it again

**Comment by twitu** [comment]
@abhisharma76 the git command line is far more powerful than the web interface. Such trivial issues will not occur if you use the command line to commit your code.

**Comment by twitu** [comment]
@abhisharma76 please make the code merge ready by putting all the files in single directory of your name. You will have to use the git CLI to do this. Follow any simple tutorial on making a GitHub PR, to make the change.

I think it is better if you do make a new PR for rather than flogging this one, so I'll close this.

**Pull request closed without merging**
